// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/MissionControlBentoDashboard-4ilUJX/Dashboard.tsx": () => import("../components/mockups/templates/MissionControlBentoDashboard-4ilUJX/Dashboard.tsx"),
  "./components/mockups/templates/OrangePortraitEventPoster-ohr-Dt/DeepOrangePoster.tsx": () => import("../components/mockups/templates/OrangePortraitEventPoster-ohr-Dt/DeepOrangePoster.tsx"),
  "./components/mockups/templates/SeveranceDinnerPartyInvite-VomkN4/DinnerPartyPosterSeverance.tsx": () => import("../components/mockups/templates/SeveranceDinnerPartyInvite-VomkN4/DinnerPartyPosterSeverance.tsx"),
  "./components/mockups/templates/SeveranceDinnerPartyInvite-lpY9-v/DinnerPartyPosterSeverance.tsx": () => import("../components/mockups/templates/SeveranceDinnerPartyInvite-lpY9-v/DinnerPartyPosterSeverance.tsx")
};
